title: <p align="center"> Monika Jhajhra </p>

logo: "portfolio image.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/monika-jhajhra-2b8431214/">LinkedIn</a> |
  <a href="https://github.com/Monika-Jhajhra">GitHub</a> |
  <a href="https://medium.com/@monikaofficial1312">Medium</a>
  </p>
  
  <p align="justify">
  I have completed Bachleors degree in Mathematics and Statistics at Banasthali Vidyapith University (Rajasthan).
  <br><br>
  I am currently looking for a job in Data Analytics and honing my skills by participating in competitions and challenges.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
